{% set name = "rastervision-core" %}
{% set version = "0.21.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rastervision_core-{{ version }}.tar.gz
  sha256: bc1dbcfe04fb0e4aec9d0ea5680f69c995907aa1a12101593958be44590824ae
  patches:
    - 0001-fix-imports.patch

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - rastervision=rastervision.core.cli:predict

requirements:
  host:
    - pip
    - python {{ python_min }}
    - opencv
  run:
    - python >={{ python_min }}
    - opencv
    - imageio ==2.3.*
    - mask-to-polygons ==0.0.2
    - numpy
    - pillow
    - pyproj ==2.6.*
    - pystac
    - rasterio
    - rastervision-pipeline
    - scikit-learn
    - shapely ==1.6.*
    - supermercado ==0.0.*


test:
  requires:
    - python {{ python_min }}
  imports:
    - rastervision
#  commands: removed due to incompatibility with opencv
#    - pip check
#  requires:
#    - pip

about:
  home: https://github.com/azavea/raster-vision
  summary: A rastervision plugin that adds geospatial machine learning pipelines
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - psortos
    - mxr-conda
